# Generated by Django 5.2.17 on 2026-09-24 18:25

import apps.projects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0002_seed_whatsapp_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("client_name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[("RUNNING", "Running"), ("COMPLETED", "Completed")],
                        default="RUNNING",
                        max_length=12,
                    ),
                ),
                (
                    "sanctioned_budget",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("expected_end_date", models.DateField(blank=True, null=True)),
                ("scope", models.TextField(blank=True)),
                (
                    "alert_state",
                    models.CharField(
                        choices=[
                            ("OK", "On track"),
                            ("WARN", "Near limit"),
                            ("OVER", "Over budget"),
                        ],
                        default="OK",
                        max_length=5,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project",
                        to="leads.lead",
                    ),
                ),
                (
                    "pm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATERIALS", "Materials"),
                            ("LABOUR", "Labour"),
                            ("TRANSPORT", "Transport"),
                            ("EQUIPMENT", "Equipment"),
                            ("FOOD", "Food"),
                            ("PERMITS", "Permits"),
                            ("OTHER", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("spent_on", models.DateField()),
                ("vendor", models.CharField(blank=True, max_length=150)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        storage=apps.projects.models.ReceiptStorage,
                        upload_to=apps.projects.models.receipt_path,
                    ),
                ),
                ("receipt_kind", models.CharField(blank=True, max_length=5)),
                ("receipt_type", models.CharField(blank=True, max_length=30)),
                ("is_override", models.BooleanField(default=False)),
                ("override_reason", models.CharField(blank=True, max_length=300)),
                ("is_void", models.BooleanField(default=False)),
                ("void_reason", models.CharField(blank=True, max_length=300)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-spent_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Project created"),
                            ("PM_ASSIGNED", "Project manager assigned"),
                            ("BUDGET_CHANGED", "Budget changed"),
                            ("EXPENSE_ADDED", "Expense added"),
                            ("EXPENSE_EDITED", "Expense edited"),
                            ("EXPENSE_VOIDED", "Expense voided"),
                            ("COMPLETED", "Project completed"),
                            ("REOPENED", "Project reopened"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status", "pm"], name="project_status_pm"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["project", "is_void", "spent_on"], name="expense_proj_void_date"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["logged_by"], name="expense_logged_by"),
        ),
        migrations.AddIndex(
            model_name="projectevent",
            index=models.Index(
                fields=["project", "-created_at"], name="event_project_time"
            ),
        ),
    ]
