# Generated by Django 5.2.17 on 2026-09-25 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Project created"),
                    ("PM_ASSIGNED", "Project manager assigned"),
                    ("BUDGET_CHANGED", "Budget changed"),
                    ("EXPENSE_ADDED", "Expense added"),
                    ("EXPENSE_EDITED", "Expense edited"),
                    ("EXPENSE_VOIDED", "Expense voided"),
                    ("COMPLETED", "Project completed"),
                    ("REOPENED", "Project reopened"),
                    ("BUDGET_REQUESTED", "Extra budget requested"),
                    ("BUDGET_DECIDED", "Budget request decided"),
                    ("BUDGET_RELEASED", "Unused budget released"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BudgetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reason", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status", "project"], name="budget_req_status")
                ],
            },
        ),
    ]
