# Generated by Django 5.2.17 on 2026-09-26 14:05
"""The sanctioned budget no longer exists: a project is measured against its deal total (Admin
only) and a Project Manager never sees any budget. Removes the budget, the alert state, expense
overrides and budget requests, plus timeline events and notifications of the removed budget types.
"""

from django.db import migrations, models

REMOVED_EVENT_TYPES = ("BUDGET_CHANGED", "BUDGET_REQUESTED", "BUDGET_DECIDED", "BUDGET_RELEASED")
REMOVED_NOTIFICATION_TYPES = (
    "budget_warn",
    "budget_over",
    "budget_requested",
    "budget_request_approved",
    "budget_request_rejected",
    "budget_changed",
)


def drop_budget_history(apps, schema_editor):
    apps.get_model("projects", "ProjectEvent").objects.filter(type__in=REMOVED_EVENT_TYPES).delete()
    try:
        notification = apps.get_model("notifications", "Notification")
    except LookupError:
        return
    notification.objects.filter(type__in=REMOVED_NOTIFICATION_TYPES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_projectevent_type_budgetrequest"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(drop_budget_history, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="expense",
            name="is_override",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="override_reason",
        ),
        migrations.RemoveField(
            model_name="project",
            name="alert_state",
        ),
        migrations.RemoveField(
            model_name="project",
            name="sanctioned_budget",
        ),
        migrations.AlterField(
            model_name="projectevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Project created"),
                    ("PM_ASSIGNED", "Project manager assigned"),
                    ("EXPENSE_ADDED", "Expense added"),
                    ("EXPENSE_EDITED", "Expense edited"),
                    ("EXPENSE_VOIDED", "Expense voided"),
                    ("COMPLETED", "Project completed"),
                    ("REOPENED", "Project reopened"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="BudgetRequest",
        ),
    ]
