# Generated by Django 5.2.17 on 2026-09-26 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_must_change_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="commission_rate",
        ),
    ]
