"""Tax invoices the admin makes for clients. Standalone: no link to leads or projects, because an
invoice's name and company can differ from the project it is for."""

from django.conf import settings
from django.db import models

from apps.core.models import TimeStampedModel


class TaxType(models.TextChoices):
    IGST = "IGST", "IGST"
    CGST_SGST = "CGST_SGST", "CGST + SGST"


class Invoice(TimeStampedModel):
    # Typed by the admin, never generated by the system.
    invoice_no = models.CharField(max_length=60, unique=True)
    # An editable name for the invoice (the project / job), used in lists, search and emails.
    title = models.CharField(max_length=200)
    invoice_date = models.DateField()

    # Bill to / ship to
    client_name = models.CharField(max_length=150)
    client_address = models.TextField(blank=True)
    client_gstin = models.CharField(max_length=20, blank=True)
    client_phone = models.CharField(max_length=20, blank=True)
    client_email = models.EmailField(blank=True)

    # GST: the admin decides the percentage per invoice; blank means no GST.
    tax_type = models.CharField(max_length=10, choices=TaxType.choices, default=TaxType.IGST)
    gst_percent = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    # Calculated and stored when the invoice is saved.
    subtotal = models.DecimalField(max_digits=14, decimal_places=2, default=0)
    tax_amount = models.DecimalField(max_digits=14, decimal_places=2, default=0)
    round_off = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=14, decimal_places=2, default=0)

    emailed_at = models.DateTimeField(null=True, blank=True)
    whatsapp_at = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL, related_name="+"
    )

    class Meta:
        ordering = ["-invoice_date", "-id"]

    def __str__(self) -> str:
        return f"Invoice {self.invoice_no}"


class InvoiceItem(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name="items")
    position = models.PositiveSmallIntegerField()
    particulars = models.TextField()
    hsn = models.CharField(max_length=20, blank=True)
    quantity = models.DecimalField(max_digits=14, decimal_places=4)  # 8,304.0948 sq.ft
    rate = models.DecimalField(max_digits=12, decimal_places=2)
    unit = models.CharField(max_length=20, blank=True)
    amount = models.DecimalField(max_digits=14, decimal_places=2)

    class Meta:
        ordering = ["position", "id"]

    def __str__(self) -> str:
        return f"{self.invoice_no} - item {self.position + 1}"
