# Generated by Django 5.2.17 on 2026-09-24 19:59

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0002_seed_whatsapp_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("finalized_on", models.DateField(blank=True, null=True)),
                ("finalize_note", models.CharField(blank=True, max_length=300)),
                ("overdue_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Ledger created"),
                            ("FINALIZED", "Total finalized"),
                            ("TOTAL_REVISED", "Total revised"),
                            ("PAYMENT_ADDED", "Payment recorded"),
                            ("PAYMENT_VOIDED", "Payment voided"),
                            ("REMINDER_SENT", "Reminder sent"),
                        ],
                        max_length=16,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="accounts.ledger",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("UPI", "UPI"),
                            ("CHEQUE", "Cheque"),
                            ("CARD", "Card"),
                            ("OTHER", "Other"),
                        ],
                        max_length=14,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("received_on", models.DateField()),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "proof",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        storage=apps.accounts.models.ProofStorage,
                        upload_to=apps.accounts.models.proof_path,
                    ),
                ),
                ("proof_kind", models.CharField(blank=True, max_length=5)),
                ("proof_type", models.CharField(blank=True, max_length=30)),
                ("is_void", models.BooleanField(default=False)),
                ("void_reason", models.CharField(blank=True, max_length=300)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="accounts.ledger",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_on", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="ledger",
            index=models.Index(fields=["finalized_at"], name="ledger_finalized_at"),
        ),
        migrations.AddIndex(
            model_name="ledgerevent",
            index=models.Index(
                fields=["ledger", "-created_at"], name="ledgerevent_time"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["ledger", "is_void", "received_on"],
                name="payment_ledger_void_date",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["received_on"], name="payment_received_on"),
        ),
    ]
