# Generated by Django 5.2.17 on 2026-09-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_seed_email_and_call_templates'),
        ('leads', '0005_drop_lead_deal_fields'),
    ]

    operations = [
    ]
