# Generated by Django 5.2.17 on 2026-10-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_merge_20260930_2325"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("CALL", "Call"),
                    ("WHATSAPP", "WhatsApp"),
                    ("EMAIL", "Email"),
                    ("MEETING", "Meeting"),
                    ("NOTE", "Note"),
                    ("STATUS_CHANGE", "Status change"),
                    ("ASSIGNMENT", "Assignment"),
                    ("AMOUNT_CHANGE", "Amount change"),
                    ("FINALIZED", "Amount finalized"),
                ],
                max_length=20,
            ),
        ),
    ]
