# Generated by Django 5.2.17 on 2026-10-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_finalized_interaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagelog",
            name="mail_ref",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="messagelog",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPENED", "Opened"),
                    ("QUEUED", "Queued"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="OPENED",
                max_length=20,
            ),
        ),
    ]
