# Generated by Django 5.2.17 on 2026-10-06 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_no", models.CharField(max_length=60, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("invoice_date", models.DateField()),
                ("client_name", models.CharField(max_length=150)),
                ("client_address", models.TextField(blank=True)),
                ("client_gstin", models.CharField(blank=True, max_length=20)),
                ("client_phone", models.CharField(blank=True, max_length=20)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                (
                    "tax_type",
                    models.CharField(
                        choices=[("IGST", "IGST"), ("CGST_SGST", "CGST + SGST")],
                        default="IGST",
                        max_length=10,
                    ),
                ),
                (
                    "gst_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "round_off",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                ("whatsapp_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("particulars", models.TextField()),
                ("hsn", models.CharField(blank=True, max_length=20)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
    ]
